// Generated by CoffeeScript 1.6.2
(function() {
  var codeBlockGenerator, generateCode;

  codeBlockGenerator = require("./codeBlockGenerator.coffee");

  generateCode = function(AST) {
    var root;

    root = Clause.fromASTNode(AST);
    return root.generateCode();
  };

  exports.generateCode = generateCode;

}).call(this);
