// Generated by CoffeeScript 1.6.2
(function() {
  var AST, ast, blocks, file, fs, testFiles, _i, _len;

  fs = require("fs");

  ast = require("./ast.coffee");

  testFiles = ["test1.cs"];

  for (_i = 0, _len = testFiles.length; _i < _len; _i++) {
    file = testFiles[_i];
    blocks = ast.parseBlock(fs.readFileSync(file).toString());
    console.log(blocks);
    AST = ast.buildAST(blocks, 0);
    console.log(AST);
  }

}).call(this);
